server:
  port: 8080
  api:
    path: /api

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    initialization-mode: always
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    schema:
      - classpath:schema-postgresql.sql
